# This workflow will install Python dependencies, run tests, and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os-version:
          - {python: "3.9", os: "ubuntu-22.04"}
          - {python: "3.10", os: "ubuntu-latest"}
          - {python: "3.11", os: "ubuntu-latest"}
          - {python: "3.12", os: "ubuntu-latest"}
          - {python: "3.13", os: "ubuntu-latest"}
          - {python: "3.14", os: "ubuntu-latest"}

    runs-on: ${{ matrix.os-version.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.os-version.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.os-version.python-version }}

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"